services:
  - type: web
    name: phishguard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///phishguard.db
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: ALERT_FROM_EMAIL
        sync: false
